#! /bin/bash

CHAPTER_DIR=chapters
CLOUD_DIR="$HOME"/Git/CloudNotes
ROOT_DIR="$CLOUD_DIR"/Assignments

REACT_DIR="$ROOT_DIR"/React
JSON_DIR="$ROOT_DIR"/Json
MIDTERM_DIR="$ROOT_DIR"/MidtermFinal
GIT_DIR="$ROOT_DIR"/Git
ISIT322_DIR="$CLOUD_DIR"/Isit322

function copyChapter() {
    cp -v "$ROOT_DIR"/"$1" "$CHAPTER_DIR"/"$2"
}

function linkChapter() {
    ln -s $3/$1 "$CHAPTER_DIR"/"$2"
}

function linkJsonChapter() {
    ln -s $JSON_DIR/$1 "$CHAPTER_DIR"/"$2"
}


if ls "$CHAPTER_DIR"/chapter_*.md 1> /dev/null 2>&1; then
    echo 'removing old chapter files'
    rm "$CHAPTER_DIR"/chapter_*.md
fi

linkChapter ReactBasics.md chapter_01.md "$REACT_DIR"
linkChapter JestCreateReactApp.md chapter_02.md "$REACT_DIR"
linkChapter RestTests.md chapter_03.md "$REACT_DIR"
linkChapter RestBasics.md chapter_04.md "$REACT_DIR"
linkChapter ReactProps.md chapter_05.md "$REACT_DIR"
linkChapter UnitTestNumbers.md chapter_06.md "$REACT_DIR"
linkChapter ReactPropsRefine.md chapter_07.md "$REACT_DIR"
linkChapter ReactPropsMounted.md chapter_08.md "$REACT_DIR"
linkChapter ReactPropsShow.md chapter_09.md "$REACT_DIR"
linkChapter ConvertJsonToFieldDefinitions.md chapter_10.md "$JSON_DIR"
linkChapter ReactGitMenu.md chapter_11.md "$REACT_DIR"
linkChapter GitMerge.md chapter_12.md "$GIT_DIR"
linkChapter GitHubApi.md chapter_13.md "$GIT_DIR"
linkChapter Isit322Midterm2017.md chapter_14.md "$MIDTERM_DIR"
# linkChapter  chapter_0.md
