var elfUtils = require('elven-code').elfUtils;

function getStarted() {
    var startEs6StringLiteralWithBackTicks = `
#! /bin/bash

# This file was autogenerated by createScripts/BuildCopyJs.js

CHAPTER_DIR=chapters
SRC_DIR="$HOME"/Git/writings/Elvenware/development/web/JavaScript

function linkChapter() {
    ln -s "$3"/"$1" "$CHAPTER_DIR"/"$2"
}

if ls "$CHAPTER_DIR"/chapter_*.md 1> /dev/null 2>&1; then
    echo 'removing old chapter files'
    rm "$CHAPTER_DIR"/chapter_*.md
fi
`;

    console.log(startEs6StringLiteralWithBackTicks);
}

var chapters = [
    "GettingStarted.md",
    "WritingSimpleCode.md",
    "JavaScriptBasics.md",
    "JavaScriptObjects.md",
    "JavaScriptFunctions.md",
    "JavaScriptModules.md",
    "DataStructures.md",
    "JavaScriptPatterns.md",
    "JsonBasics.md",
    "JQueryBasic.md",
    "JQueryUi.md",
    "NodeJs.md",
    "NodePackages.md",
    "NodeJade.md",
    "ElvenUtilities.md",
    "JavaScriptReact.md",
    "JavaScriptReactMenu.md",
    "Angular.md",
    "Require.md",
    "HandleBars.md",
    "Sockets.md",
    "Functional.md"
]

getStarted();

chapters.forEach(function(item, index) {
    console.log('linkChapter ' + item + ' chapter_' + elfUtils.padNumber(index + 1, 2, '0') + '.md "$SRC_DIR"');
});
